apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: cpu-default
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: code-runner-cq
spec:
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: cpu-default
          resources:
            - name: cpu
              nominalQuota: "4"
            - name: memory
              nominalQuota: 4Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: code-runner-queue
  namespace: code-runner-system
spec:
  clusterQueue: code-runner-cq
