apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-runner-api
  namespace: code-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: code-runner-role
  namespace: code-runner-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-runner-rolebinding
  namespace: code-runner-system
subjects:
  - kind: ServiceAccount
    name: code-runner-api
    namespace: code-runner-system
roleRef:
  kind: Role
  name: code-runner-role
  apiGroup: rbac.authorization.k8s.io
